version: 2.1

workflows:
  main:
    jobs:
      - build

orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - node/install:
          node-version: '12.18.1'
      - browser-tools/install-chrome:
          replace-existing: true
      - run:
          name: Start Services
          command: npm run services:start
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Connect to Services
          command: npm run connect
      - run:
          name: Test
          command: npm test
